{{ if .Values.coredns_mappings }}
apiVersion: v1
data:
  hosts.override: |
    {{ .Values.cluster_domain }}:53 {
    hosts {
        {{ range .Values.coredns_mappings }}
        {{ .coredns_ip }} {{ .subdomain }}.{{ $.Values.cluster_domain }}
        {{ end }}
        fallthrough
      }
    }
kind: ConfigMap
metadata:
  labels:
    k0s.k0sproject.io/stack: coredns
  name: coredns-custom
  namespace: kube-system
{{ end }}