#SPDX-License-Identifier: MIT-0
---
- name: Include environment variables
  ansible.builtin.include_vars:
    file: "{{ config_folder }}/env.json"
  when: config_folder is defined

- name: Ensure pip is installed
  ansible.builtin.package:
    name: python3-pip
    state: present
  become: true

- name: Ensure the 'python3-kubernetes' system package is installed
  ansible.builtin.package:
    name: python3-kubernetes
    state: present
  become: true

- name: Ensure ArgoCD namespace exists
  ansible.builtin.command: >
    {{ kubernetes_kubectl_cmd }} create namespace "{{ argocd_namespace }}"
  register: create_argocd_ns
  failed_when: create_argocd_ns.rc != 0 and 'AlreadyExists' not in (create_argocd_ns.stderr | default(''))
  changed_when: "'Created' in (create_argocd_ns.stdout | default(''))"
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ DEPLOY_KUBECONFIG }}"

- name: Update ArgoCD initial admin secret
  ansible.builtin.command: >
    {{ kubernetes_kubectl_cmd }} -n "{{ argocd_namespace }}"
    create secret generic argocd-secret
    --from-literal=admin.password="{{ argocd_bcrypt_password }}"
    --from-literal=admin.passwordMtime="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  register: argocd_secret_create
  failed_when: argocd_secret_create.rc != 0 and 'already exists' not in (argocd_secret_create.stderr | default(''))
  changed_when: '"already exists" not in argocd_secret_create.stderr'
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ argocd_kubeconfig }}"

- name: Install ArgoCD manifests
  ansible.builtin.command: >
    {{ kubernetes_kubectl_cmd }} apply -n "{{ argocd_namespace }}" --server-side --force-conflicts -f "{{ argocd_manifest_url }}"
  register: apply_argocd_manifests
  # Do not fail on 'Too long' CRD annotation error or annotation warnings
  failed_when: >
    apply_argocd_manifests.rc != 0 and
    (
      "metadata.annotations: Too long:" not in (apply_argocd_manifests.stderr | default('')) and
      "is missing the kubectl.kubernetes.io/last-applied-configuration annotation" not in (apply_argocd_manifests.stderr | default(''))
    )
  changed_when: "'created' in (apply_argocd_manifests.stdout | default(''))"
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ DEPLOY_KUBECONFIG }}"

- name: Display ArgoCD UI URL
  ansible.builtin.debug:
    msg: "ArgoCD UI: {{ argocd_ui_url }}"

- name: Ensure automation service account exists
  ansible.builtin.command: >
    {{ kubernetes_kubectl_cmd }} create serviceaccount "{{ argocd_service_account }}" -n "{{ argocd_namespace }}"
  register: create_argocd_service_account
  failed_when: create_argocd_service_account.rc != 0 and
    (
      'AlreadyExists' not in (create_argocd_service_account.stderr | default('')) and
      'already exists' not in (create_argocd_service_account.stderr | default(''))
    )
  changed_when: "'Created' in (create_argocd_service_account.stdout | default(''))"
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ argocd_kubeconfig }}"

- name: Ensure RoleBinding for automation service account exists
  ansible.builtin.command: >
    {{ kubernetes_kubectl_cmd }} create rolebinding "{{ argocd_service_account }}-binding" -n "{{ argocd_namespace }}" --serviceaccount="{{ argocd_service_account }}:{{ argocd_namespace }}" --clusterrole="{{ argocd_role_name }}"
  register: create_argocd_role_binding
  failed_when: create_argocd_role_binding.rc != 0 and 'AlreadyExists' not in (create_argocd_role_binding.stderr | default(''))
  changed_when: "'Created' in (create_argocd_role_binding.stdout | default(''))"
  failed_when: create_argocd_role_binding.rc != 0 and
    (
      'AlreadyExists' not in (create_argocd_role_binding.stderr | default('')) and
      'already exists' not in (create_argocd_role_binding.stderr | default(''))
    )
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ argocd_kubeconfig }}"

- name: Ensure extra_commands is a list
  set_fact:
    _extra_commands_list: >-
      {% if extra_commands is defined and extra_commands is string %}
        {{ extra_commands | trim(" []") | replace("'", "") | split(", ") }}
      {% elif extra_commands is defined and extra_commands is sequence %}
        {{ extra_commands }}
      {% else %}
        []
      {% endif %}
 
- name: Debug _extra_commands_list
  ansible.builtin.debug:
    var: _extra_commands_list

- name: Run additional commands
  ansible.builtin.command: "{{ item }}"
  loop: "{{ _extra_commands_list }}"
  when: _extra_commands_list is defined and (_extra_commands_list | length > 0)
  register: extra_commands_result
  changed_when: false
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ argocd_kubeconfig }}"

- name: Run additional ArgoCD connect tasks
  import_tasks: connect.yml
