- name: Fix too many open files error
  hosts: all
  tasks:
    - name: Fix too many open files error
      shell: |
        sysctl -w fs.inotify.max_user_instances=1280
        sysctl -w fs.inotify.max_user_watches=655360
      register: result
      changed_when: false
      failed_when: false
    - name: Print result
      debug:
        msg: "{{ result.stdout }}"