{{- if .Values.maiaAgent.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "maia-pacs-stack.maiaAgentPvcName" . }}
  labels:
    {{- include "maia-pacs-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: maia-agent
spec:
  accessModes:
    - {{ .Values.maiaAgent.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.maiaAgent.persistence.size }}
  {{- if .Values.maiaAgent.persistence.storageClass }}
  storageClassName: {{ .Values.maiaAgent.persistence.storageClass }}
  {{- end }}
{{- end }}
