apiVersion: v1
kind: Service
metadata:
  name: {{ include "maia-pacs-stack.fullname" . }}-ohif
  labels:
    {{- include "maia-pacs-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: ohif
spec:
  type: {{ .Values.ohif.service.type }}
  ports:
    - port: {{ .Values.ohif.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "maia-pacs-stack.ohifSelectorLabels" . | nindent 4 }}
