apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "maia-pacs-stack.ohifConfigMapName" . }}
  labels:
    {{- include "maia-pacs-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: ohif
data:
  ohif-entrypoint.sh: |
{{ .Files.Get "files/maia-ohif-entrypoint.sh" | indent 4 }}
  ohif-config.js.template: |
{{ .Files.Get "files/ohif-config.js.template" | indent 4 }}
  ohif-default.conf.template: |
    server {
      gzip_static  always;
      gzip_proxied expired no-cache no-store private auth;
      gunzip       on;
      listen ${PORT} default_server;
      listen [::]:${PORT} default_server;

      location ${DICOMWEB_PUBLIC_PATH}/ {
        proxy_pass http://{{ include "maia-pacs-stack.orthancUpstreamHost" . }}:{{ .Values.orthanc.service.targetPort }}/dicom-web/;
        proxy_set_header Host $host;
        proxy_request_buffering off;
        proxy_max_temp_file_size 0;
        client_max_body_size 0;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Accept,Origin' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range,Content-Type' always;

        if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Allow-Origin' '*';
          add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
          add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Accept,Origin';
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain; charset=utf-8';
          add_header 'Content-Length' 0;
          return 204;
        }
      }

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
        add_header Cross-Origin-Resource-Policy same-origin;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
