{{- if .Values.orthanc.persistence.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "maia-pacs-stack.orthancStoragePvcName" . }}
  labels:
    {{- include "maia-pacs-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: orthanc
spec:
  accessModes:
    - {{ .Values.orthanc.persistence.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.orthanc.persistence.storage.size }}
  {{- if .Values.orthanc.persistence.storage.storageClass }}
  storageClassName: {{ .Values.orthanc.persistence.storage.storageClass }}
  {{- end }}
{{- end }}
