apiVersion: v1
kind: Service
metadata:
  name: {{ include "maia-pacs-stack.fullname" . }}-postgres
  labels:
    {{- include "maia-pacs-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "maia-pacs-stack.postgresSelectorLabels" . | nindent 4 }}
