# Generated by Django 4.2.30 on 2026-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_resource_needs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maiaproject',
            name='conda',
        ),
        migrations.RemoveField(
            model_name='maiaproject',
            name='minimal_env',
        ),
        migrations.AddField(
            model_name='maiaproject',
            name='auto_deploy',
            field=models.BooleanField(default=False, verbose_name='auto_deploy'),
        ),
        migrations.AddField(
            model_name='maiaproject',
            name='auto_deploy_apps',
            field=models.JSONField(default=list, null=True, verbose_name='auto_deploy_apps'),
        ),
        migrations.AddField(
            model_name='maiaproject',
            name='cpu_request',
            field=models.TextField(default='2', null=True, verbose_name='cpu_request'),
        ),
        migrations.AddField(
            model_name='maiaproject',
            name='email_to_username_map',
            field=models.JSONField(default=dict, null=True, verbose_name='email_to_username_map'),
        ),
        migrations.AddField(
            model_name='maiaproject',
            name='memory_request',
            field=models.TextField(default='2 Gi', null=True, verbose_name='memory_request'),
        ),
        migrations.AddField(
            model_name='maiaproject',
            name='project_configuration',
            field=models.JSONField(default=dict, null=True, verbose_name='project_configuration'),
        ),
        migrations.AddField(
            model_name='maiaproject',
            name='project_tier',
            field=models.TextField(default='Base', null=True, verbose_name='project_tier'),
        ),
        migrations.AddField(
            model_name='maiaproject',
            name='users',
            field=models.JSONField(default=list, null=True, verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='maiaproject',
            name='memory_limit',
            field=models.TextField(default='2 Gi', null=True, verbose_name='memory_limit'),
        ),
    ]
